FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal AS base
WORKDIR /app
EXPOSE 80

ENV ASPNETCORE_URLS=http://+:80

FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build
WORKDIR /src
COPY [$(Build.Repository.LocalPath)/TestNet.app/TestNet.app.csproj, "TestNet.app/"]
RUN dotnet restore "TestNet.app/TestNet.app.csproj"
COPY . .
WORKDIR "/src/TestNet.app"
RUN dotnet build "TestNet.app.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TestNet.app.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TestNet.app.dll"] 